"use client";

import { cn } from "@/lib/utils";
import { motion } from "motion/react";
import ReactMarkdown from "react-markdown";
import {
    ArrowLeft,
    Clock,
    Calendar,
    FileText,
    Brain,
    CheckCircle2,
    AlertCircle,
    User,
    Stethoscope,
    Pill,
} from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

interface ReportPageClientProps {
    report: {
        id: string;
        summary: string;
        urgencyLevel: string;
        recommendedAction: string;
        reasoningChain: string | null;
        confidenceScore: number;
        suggestedICD10: string[];
        suggestedCPT: string[];
        status: string;
        createdAt: string;
        encounter: {
            id: string;
            symptoms: string;
            voiceTranscript: string | null;
            chiefComplaint: string | null;
            createdAt: string;
            patient: {
                id: string;
                name: string;
                gender: string;
                dateOfBirth: string;
                medicalHistorySummary: string | null;
                medications: {
                    id: string;
                    name: string;
                    dosage: string | null;
                    status: string;
                }[];
                medicalHistory: {
                    id: string;
                    description: string;
                    category: string;
                }[];
            };
        };
    };
}

const urgencyColors: Record<string, string> = {
    CRITICAL: "bg-danger text-white",
    HIGH: "bg-warning text-primary-foreground",
    MEDIUM: "bg-info text-primary-foreground",
    LOW: "bg-success text-primary-foreground",
};

function calculateAge(dateOfBirth: string): number {
    const today = new Date();
    const dob = new Date(dateOfBirth);
    let age = today.getFullYear() - dob.getFullYear();
    const monthDiff = today.getMonth() - dob.getMonth();
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < dob.getDate())) {
        age--;
    }
    return age;
}

export function ReportPageClient({ report }: ReportPageClientProps) {
    const router = useRouter();
    const [isApproving, setIsApproving] = useState(false);

    const patient = report.encounter.patient;
    const age = calculateAge(patient.dateOfBirth);
    const activeMedications = patient.medications.filter(m => m.status === "active");

    const handleApprove = async () => {
        setIsApproving(true);
        try {
            const response = await fetch(`/api/reports/${report.id}/approve`, {
                method: "POST",
            });
            if (response.ok) {
                router.refresh();
            }
        } catch (error) {
            console.error("Failed to approve report:", error);
        } finally {
            setIsApproving(false);
        }
    };

    return (
        <div className="space-y-6">
            {/* Back Button & Header */}
            <div className="flex items-center gap-4">
                <Link
                    href="/dashboard/reports"
                    className="flex h-10 w-10 items-center justify-center rounded-lg border border-border bg-surface-1 text-muted-foreground transition-colors hover:bg-surface-2 hover:text-foreground"
                >
                    <ArrowLeft className="h-4 w-4" />
                </Link>
                <div className="flex-1">
                    <div className="flex items-center gap-3">
                        <h1 className="text-2xl font-bold tracking-tight text-foreground font-display">
                            Triage Report
                        </h1>
                        <span className="font-mono text-sm text-muted-foreground">
                            #{report.id.slice(0, 8)}
                        </span>
                        <span
                            className={cn(
                                "inline-flex items-center rounded-lg px-2.5 py-0.5 text-xs font-semibold",
                                urgencyColors[report.urgencyLevel]
                            )}
                        >
                            {report.urgencyLevel}
                        </span>
                        <span className={cn(
                            "rounded-lg px-2 py-0.5 text-xs font-medium",
                            report.status === "DRAFT"
                                ? "bg-warning/10 text-warning"
                                : "bg-success/10 text-success"
                        )}>
                            {report.status}
                        </span>
                    </div>
                    <p className="mt-1 text-sm text-muted-foreground">
                        Generated by Med-Gemini AI on {new Date(report.createdAt).toLocaleDateString()} at{" "}
                        {new Date(report.createdAt).toLocaleTimeString()}
                    </p>
                </div>
                <div className="flex items-center gap-2">
                    <button className="flex items-center gap-2 rounded-lg border border-border bg-surface-1 px-4 py-2.5 text-sm font-medium text-foreground transition-colors hover:bg-surface-2">
                        <FileText className="h-4 w-4" />
                        Export
                    </button>
                    {report.status === "DRAFT" && (
                        <motion.button
                            whileHover={{ scale: 1.02 }}
                            whileTap={{ scale: 0.98 }}
                            onClick={handleApprove}
                            disabled={isApproving}
                            className="flex items-center gap-2 rounded-lg bg-success px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-success/20 disabled:opacity-50"
                        >
                            <CheckCircle2 className="h-4 w-4" />
                            {isApproving ? "Approving..." : "Approve & Finalize"}
                        </motion.button>
                    )}
                </div>
            </div>

            {/* Main Content Grid */}
            <div className="grid gap-6 lg:grid-cols-3">
                {/* Left Column - Patient & Encounter Info */}
                <div className="space-y-4">
                    {/* Patient Card */}
                    <div className="glass-card p-5">
                        <h3 className="mb-4 flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-muted">
                            <User className="h-4 w-4" />
                            Patient Information
                        </h3>
                        <div className="space-y-3">
                            <div>
                                <p className="text-2xl font-bold text-foreground">
                                    {patient.name}
                                </p>
                                <p className="text-sm text-muted-foreground">
                                    {age} years, {patient.gender}
                                </p>
                            </div>
                            <div className="flex items-center gap-2 text-sm text-muted-foreground">
                                <Calendar className="h-4 w-4" />
                                DOB: {new Date(patient.dateOfBirth).toLocaleDateString()}
                            </div>
                            <Link
                                href={`/dashboard/patients/${patient.id}`}
                                className="inline-flex items-center gap-1 text-sm text-primary hover:underline"
                            >
                                View Full Profile →
                            </Link>
                        </div>
                    </div>

                    {/* Active Medications */}
                    {activeMedications.length > 0 && (
                        <div className="glass-card p-5">
                            <h3 className="mb-4 flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-muted">
                                <Pill className="h-4 w-4 text-info" />
                                Active Medications
                            </h3>
                            <ul className="space-y-2">
                                {activeMedications.slice(0, 5).map(med => (
                                    <li key={med.id} className="flex items-center gap-2 text-sm">
                                        <span className="h-1.5 w-1.5 rounded-full bg-info" />
                                        <span className="text-foreground">{med.name}</span>
                                        {med.dosage && (
                                            <span className="text-muted-foreground">{med.dosage}</span>
                                        )}
                                    </li>
                                ))}
                                {activeMedications.length > 5 && (
                                    <li className="text-sm text-muted-foreground">
                                        +{activeMedications.length - 5} more
                                    </li>
                                )}
                            </ul>
                        </div>
                    )}

                    {/* Encounter Card */}
                    <div className="glass-card p-5">
                        <h3 className="mb-4 flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-muted">
                            <Stethoscope className="h-4 w-4" />
                            Current Encounter
                        </h3>
                        <div className="space-y-4">
                            <div>
                                <p className="text-xs font-medium uppercase text-muted">
                                    Chief Complaint / Symptoms
                                </p>
                                <p className="mt-1 text-sm text-foreground">
                                    {report.encounter.chiefComplaint || report.encounter.symptoms}
                                </p>
                            </div>
                            {report.encounter.voiceTranscript && (
                                <div>
                                    <p className="text-xs font-medium uppercase text-muted">
                                        Voice Transcript
                                    </p>
                                    <p className="mt-1 text-sm italic text-muted-foreground">
                                        &quot;{report.encounter.voiceTranscript}&quot;
                                    </p>
                                </div>
                            )}
                            <div className="flex items-center gap-2 text-xs text-muted-foreground">
                                <Clock className="h-3 w-3" />
                                {new Date(report.encounter.createdAt).toLocaleString()}
                            </div>
                        </div>
                    </div>

                    {/* Longitudinal Context */}
                    {patient.medicalHistorySummary && (
                        <div className="glass-card p-5">
                            <h3 className="mb-4 flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-muted">
                                <Brain className="h-4 w-4 text-info" />
                                Longitudinal History
                                <span className="ml-auto rounded-lg bg-info/10 px-2 py-0.5 text-[10px] font-medium text-info">
                                    AI Generated
                                </span>
                            </h3>
                            <div className="text-sm leading-relaxed text-muted-foreground prose-report">
                                <ReactMarkdown>{patient.medicalHistorySummary}</ReactMarkdown>
                            </div>
                        </div>
                    )}
                </div>

                {/* Right Column - AI Analysis */}
                <div className="space-y-4 lg:col-span-2">
                    {/* Summary Card */}
                    <div className="glass-card overflow-hidden">
                        <div className="border-b border-border bg-gradient-to-r from-primary/5 to-transparent px-6 py-4">
                            <div className="flex items-center justify-between">
                                <h3 className="flex items-center gap-2 font-semibold text-foreground">
                                    <Brain className="h-5 w-5 text-primary" />
                                    AI Clinical Summary
                                </h3>
                                <div className="flex items-center gap-2">
                                    <span className="text-sm text-muted-foreground">
                                        Confidence:
                                    </span>
                                    <div className="flex items-center gap-2">
                                        <div className="h-2 w-20 overflow-hidden rounded-lg bg-surface-3">
                                            <div
                                                className={cn(
                                                    "h-full rounded-full",
                                                    (report.confidenceScore * 100) >= 90 ? "bg-success" :
                                                        (report.confidenceScore * 100) >= 75 ? "bg-info" :
                                                            (report.confidenceScore * 100) >= 50 ? "bg-warning" : "bg-danger"
                                                )}
                                                style={{
                                                    width: `${Math.round(report.confidenceScore * 100)}%`,
                                                }}
                                            />
                                        </div>
                                        <span className={cn(
                                            "font-mono text-sm font-bold",
                                            (report.confidenceScore * 100) >= 90 ? "text-success" :
                                                (report.confidenceScore * 100) >= 75 ? "text-info" :
                                                    (report.confidenceScore * 100) >= 50 ? "text-warning" : "text-danger"
                                        )}>
                                            {Math.round(report.confidenceScore * 100)}%
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="p-6 prose-report">
                            <ReactMarkdown>{report.summary}</ReactMarkdown>
                        </div>
                    </div>

                    {/* Recommended Actions */}
                    <div className="glass-card p-6">
                        <h3 className="mb-4 flex items-center gap-2 font-semibold text-foreground">
                            <AlertCircle className="h-5 w-5 text-warning" />
                            Recommended Actions
                        </h3>
                        <div className="prose-report">
                            <ReactMarkdown>{report.recommendedAction}</ReactMarkdown>
                        </div>
                    </div>

                    {/* Suggested Codes */}
                    <div className="grid gap-4 md:grid-cols-2">
                        <div className="glass-card p-5">
                            <h4 className="mb-3 text-sm font-semibold uppercase tracking-wider text-muted">
                                Suggested ICD-10 Codes
                            </h4>
                            {report.suggestedICD10.length > 0 ? (
                                <ul className="space-y-2">
                                    {report.suggestedICD10.map((code) => (
                                        <li
                                            key={code}
                                            className="rounded-lg bg-info/10 px-3 py-2 font-mono text-xs text-info"
                                        >
                                            {code}
                                        </li>
                                    ))}
                                </ul>
                            ) : (
                                <p className="text-sm text-muted-foreground">No codes suggested</p>
                            )}
                        </div>
                        <div className="glass-card p-5">
                            <h4 className="mb-3 text-sm font-semibold uppercase tracking-wider text-muted">
                                Suggested CPT Codes
                            </h4>
                            {report.suggestedCPT.length > 0 ? (
                                <ul className="space-y-2">
                                    {report.suggestedCPT.map((code) => (
                                        <li
                                            key={code}
                                            className="rounded-lg bg-success/10 px-3 py-2 font-mono text-xs text-success"
                                        >
                                            {code}
                                        </li>
                                    ))}
                                </ul>
                            ) : (
                                <p className="text-sm text-muted-foreground">No codes suggested</p>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
