/**
 * Test Patient Seed Script
 * 
 * Run with: npx tsx scripts/seed-test-patient.ts
 * 
 * Creates a comprehensive test patient profile with:
 * - Full patient demographics
 * - Medical history (conditions, allergies, surgeries)
 * - Active medications
 * - Ready for triage testing
 */

import "dotenv/config";
import { prisma } from "../src/lib/db";

async function seedTestPatient() {
    console.log("🏥 Creating Test Patient for Med-Gemini Workflow Testing...\n");

    // Check if test patient already exists
    const existing = await prisma.patient.findFirst({
        where: { name: "Maria Rodriguez" }
    });

    if (existing) {
        console.log("⚠️  Test patient 'Maria Rodriguez' already exists!");
        console.log(`   Patient ID: ${existing.id}`);
        console.log("\n🔗 Access at: http://localhost:3000/dashboard/patients/" + existing.id);
        await prisma.$disconnect();
        return;
    }

    // Create the test patient
    const patient = await prisma.patient.create({
        data: {
            name: "Maria Rodriguez",
            gender: "Female",
            dateOfBirth: new Date("1978-06-15"), // 47 years old
            email: "maria.rodriguez@example.com",
            phone: "+1-555-0147",
            address: "456 Oak Avenue, San Francisco, CA 94110",
            emergencyContactName: "Carlos Rodriguez",
            emergencyContactPhone: "+1-555-0148",
            emergencyContactRelation: "Husband",
            mrn: "MRN-789456123",

            // Medical history summary will be generated by AI during triage
            medicalHistorySummary: null,
        }
    });

    console.log(`✅ Created patient: ${patient.name}`);
    console.log(`   ID: ${patient.id}`);
    console.log(`   DOB: ${patient.dateOfBirth.toLocaleDateString()}`);

    // Add Medical History entries
    const medicalHistoryEntries = [
        {
            type: "condition",
            clinicalStatus: "active",
            description: "Type 2 Diabetes Mellitus - diagnosed 2015, well-controlled with medication",
            onsetDate: new Date("2015-03-20"),
            severity: "MODERATE",
            notes: "HbA1c consistently 6.5-7.0%. No diabetic complications noted."
        },
        {
            type: "condition",
            clinicalStatus: "active",
            description: "Essential Hypertension - diagnosed 2018",
            onsetDate: new Date("2018-08-10"),
            severity: "MILD",
            notes: "Blood pressure well-controlled on current regimen. Target BP < 130/80."
        },
        {
            type: "condition",
            clinicalStatus: "active",
            description: "Hyperlipidemia - elevated LDL cholesterol",
            onsetDate: new Date("2019-01-15"),
            severity: "MILD",
            notes: "Started statin therapy. Last LDL: 98 mg/dL."
        },
        {
            type: "allergy",
            clinicalStatus: "active",
            description: "Penicillin allergy - causes severe rash and hives",
            onsetDate: new Date("1995-07-10"),
            severity: "SEVERE",
            notes: "CRITICAL: Do not prescribe penicillin-class antibiotics. Use azithromycin or fluoroquinolones as alternatives."
        },
        {
            type: "allergy",
            clinicalStatus: "active",
            description: "Sulfa drugs allergy - causes GI upset",
            onsetDate: new Date("2010-04-22"),
            severity: "MODERATE",
            notes: "Avoid sulfonamide antibiotics."
        },
        {
            type: "surgery",
            clinicalStatus: "resolved",
            description: "Laparoscopic Cholecystectomy (gallbladder removal)",
            onsetDate: new Date("2020-11-15"),
            abatementDate: new Date("2020-11-20"),
            severity: "MILD",
            notes: "Uncomplicated procedure. Full recovery in 2 weeks."
        },
        {
            type: "surgery",
            clinicalStatus: "resolved",
            description: "Cesarean Section - delivery of second child",
            onsetDate: new Date("2005-09-12"),
            abatementDate: new Date("2005-10-01"),
            severity: "MILD",
            notes: "Uncomplicated C-section. No adhesions noted on subsequent imaging."
        },
        {
            type: "family_history",
            clinicalStatus: "active",
            description: "Mother: Type 2 Diabetes, Hypertension. Father: Coronary Artery Disease (MI at age 62). Sister: Breast cancer at age 52.",
            onsetDate: null,
            severity: "MODERATE",
            notes: "Significant family history of cardiovascular disease and diabetes. Consider increased screening."
        },
        {
            type: "social_history",
            clinicalStatus: "active",
            description: "Non-smoker and non-drinker. Works as elementary school teacher. Married with 2 children. Moderate exercise 3x/week.",
            onsetDate: null,
            severity: "MILD",
            notes: "Generally healthy lifestyle. Low stress environment."
        }
    ];

    for (const entry of medicalHistoryEntries) {
        await prisma.medicalHistory.create({
            data: {
                patientId: patient.id,
                ...entry
            }
        });
    }
    console.log(`✅ Added ${medicalHistoryEntries.length} medical history entries`);

    // Add Active Medications
    const medications = [
        {
            name: "Metformin",
            dosage: "1000mg",
            frequency: "twice daily",
            route: "oral",
            status: "active",
            reason: "Type 2 Diabetes Mellitus",
            prescribedBy: "Dr. Sarah Chen, Endocrinology",
            startDate: new Date("2015-04-01"),
            notes: "Take with meals to reduce GI side effects"
        },
        {
            name: "Lisinopril",
            dosage: "20mg",
            frequency: "once daily",
            route: "oral",
            status: "active",
            reason: "Hypertension",
            prescribedBy: "Dr. Michael Park, Primary Care",
            startDate: new Date("2018-08-15"),
            notes: "Monitor potassium levels"
        },
        {
            name: "Atorvastatin",
            dosage: "40mg",
            frequency: "once daily at bedtime",
            route: "oral",
            status: "active",
            reason: "Hyperlipidemia",
            prescribedBy: "Dr. Michael Park, Primary Care",
            startDate: new Date("2019-02-01"),
            notes: "Take at night for best efficacy"
        },
        {
            name: "Aspirin",
            dosage: "81mg",
            frequency: "once daily",
            route: "oral",
            status: "active",
            reason: "Cardiovascular protection",
            prescribedBy: "Dr. Michael Park, Primary Care",
            startDate: new Date("2019-02-01"),
            notes: "Low-dose aspirin for primary prevention given CV risk factors"
        },
        {
            name: "Vitamin D3",
            dosage: "2000 IU",
            frequency: "once daily",
            route: "oral",
            status: "active",
            reason: "Vitamin D deficiency",
            prescribedBy: "Dr. Michael Park, Primary Care",
            startDate: new Date("2022-01-15"),
            notes: "Last level: 28 ng/mL"
        }
    ];

    for (const med of medications) {
        await prisma.medication.create({
            data: {
                patientId: patient.id,
                ...med
            }
        });
    }
    console.log(`✅ Added ${medications.length} active medications`);

    console.log("\n" + "=".repeat(60));
    console.log("📋 TEST PATIENT PROFILE");
    console.log("=".repeat(60));
    console.log(`
Name:           Maria Rodriguez
Age:            47 years old (DOB: June 15, 1978)
Gender:         Female

CONDITIONS:
• Type 2 Diabetes Mellitus (active, well-controlled)
• Essential Hypertension (active)
• Hyperlipidemia (active)

ALLERGIES:
• ⚠️ Penicillin - SEVERE (rash, hives)
• ⚠️ Sulfa drugs - MODERATE (GI upset)

SURGERIES:
• Cholecystectomy (2020)
• C-Section (2005)

CURRENT MEDICATIONS:
• Metformin 1000mg BID
• Lisinopril 20mg daily
• Atorvastatin 40mg at bedtime
• Aspirin 81mg daily
• Vitamin D3 2000 IU daily

FAMILY HISTORY:
• Mother: Type 2 Diabetes, Hypertension
• Father: CAD (MI at 62)
• Sister: Breast cancer at 52
`);
    console.log("=".repeat(60));
    console.log("\n🧪 SUGGESTED TEST SCENARIOS:");
    console.log("=".repeat(60));
    console.log(`
1. CHEST PAIN TRIAGE (HIGH URGENCY):
   Symptoms: "Chest tightness and shortness of breath for the past 2 hours, 
              worse with exertion. Some left arm discomfort."
   
   Expected: High/Critical urgency due to cardiovascular risk factors
   (family history of MI, diabetes, hypertension, hyperlipidemia)

2. INFECTION SCENARIO (MEDIUM URGENCY):
   Symptoms: "Fever of 101.5°F for 2 days, productive cough with 
              yellow-green sputum, fatigue."
   
   Expected: Medium urgency, note penicillin allergy in recommendations

3. DIABETES FOLLOW-UP (LOW URGENCY):
   Symptoms: "Routine follow-up, feeling well. Occasional mild 
              tingling in feet noticed over past month."
   
   Expected: Low urgency, possible early neuropathy screening recommended
`);
    console.log("=".repeat(60));
    console.log(`\n🔗 Access patient at: http://localhost:3000/dashboard/patients/${patient.id}`);
    console.log("📤 To start triage: Click 'Start Triage' button on patient page\n");

    await prisma.$disconnect();
}

seedTestPatient().catch(e => {
    console.error("Error seeding test patient:", e);
    prisma.$disconnect();
    process.exit(1);
});
